using System;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEditor;
using UnityEngine;

namespace UnityGLTF.Interactivity.Export
{
    public class LerpClampedUnitExports : IUnitExporter
    {
        [InitializeOnLoadMethod]
        private static void Register()
        {
            InvokeUnitExport.RegisterInvokeExporter(typeof(Mathf), nameof(Mathf.Lerp), new LerpClampedUnitExports(GltfInteractivityTypeMapping.TypeIndexByGltfSignature("float")));
            InvokeUnitExport.RegisterInvokeExporter(typeof(Vector2), nameof(Vector2.Lerp), new LerpClampedUnitExports(GltfInteractivityTypeMapping.TypeIndexByGltfSignature("float2")));
            InvokeUnitExport.RegisterInvokeExporter(typeof(Vector3), nameof(Vector3.Lerp), new LerpClampedUnitExports(GltfInteractivityTypeMapping.TypeIndexByGltfSignature("float3")));
            InvokeUnitExport.RegisterInvokeExporter(typeof(Vector4), nameof(Vector4.Lerp), new LerpClampedUnitExports(GltfInteractivityTypeMapping.TypeIndexByGltfSignature("float4")));
            InvokeUnitExport.RegisterInvokeExporter(typeof(Quaternion), nameof(Quaternion.Lerp), new LerpClampedUnitExports(GltfInteractivityTypeMapping.TypeIndexByGltfSignature("float4")));
            
            // TODO: correct Slerp, currently we use Mix  
            InvokeUnitExport.RegisterInvokeExporter(typeof(Vector3), nameof(Vector3.Slerp), new LerpClampedUnitExports(GltfInteractivityTypeMapping.TypeIndexByGltfSignature("float3")));
            InvokeUnitExport.RegisterInvokeExporter(typeof(Quaternion), nameof(Quaternion.Slerp), new LerpClampedUnitExports(GltfInteractivityTypeMapping.TypeIndexByGltfSignature("float4")));
        }

        public Type unitType { get => typeof(InvokeMember); }
        private int gltfType;
        
        public LerpClampedUnitExports(int gltfType)
        {
            this.gltfType = gltfType;
        }
        
        public void InitializeInteractivityNodes(UnitExporter unitExporter)
        {
            var unit = unitExporter.unit as InvokeMember;
            var typeRestr = TypeRestriction.LimitToType(gltfType);
            var expType = ExpectedType.GtlfType(gltfType);
            
            GenericUnitExport.TryGetAutoGeneratedSchema("math/saturate", out var saturateSchema);
            var saturateNode = unitExporter.CreateNode(saturateSchema);
            saturateNode.ValueIn("a").MapToInputPort(unit.valueInputs[2]).SetType(typeRestr);
            saturateNode.FirstValueOut().ExpectedType(expType);

            GenericUnitExport.TryGetAutoGeneratedSchema("math/mix", out var mixSchema);
            var mixNode = unitExporter.CreateNode(mixSchema);
            mixNode.ValueIn("a").MapToInputPort(unit.valueInputs[0]).SetType(typeRestr);
            mixNode.ValueIn("b").MapToInputPort(unit.valueInputs[1]).SetType(typeRestr);
            mixNode.ValueIn("c").ConnectToSource(saturateNode.FirstValueOut()).SetType(typeRestr);
            mixNode.FirstValueOut().MapToPort(unit.result).ExpectedType(expType);

            unitExporter.ByPassFlow(unit.enter, unit.exit);
         }
        
    }
}