using Unity.VisualScripting;
using UnityEngine;
using UnityGLTF.Interactivity.Schema;

namespace UnityGLTF.Interactivity.Export
{
    public static class SpaceConversionHelpers
    {
        #region Position Space Conversion
        
        private static GltfInteractivityUnitExporterNode.ValueOutputSocketData AddSpaceConversionNodes(UnitExporter unitExporter, GltfInteractivityUnitExporterNode extractNode)
        {
            var multiplyNode = unitExporter.CreateNode(GenericUnitExport.GetAutoGeneratedSchema("math/mul"));
            multiplyNode.ValueIn("a").ConnectToSource(extractNode.ValueOut("0")).SetType(TypeRestriction.LimitToFloat);
            multiplyNode.ValueIn("b").SetValue(-1).SetType(TypeRestriction.LimitToFloat);
            multiplyNode.FirstValueOut().ExpectedType(ExpectedType.Float);
            
            var combineNode = unitExporter.CreateNode(GenericUnitExport.GetAutoGeneratedSchema("math/combine3"));
            combineNode.ValueIn("a").ConnectToSource(multiplyNode.FirstValueOut());
            combineNode.ValueIn("b").ConnectToSource(extractNode.ValueOut("1"));
            combineNode.ValueIn("c").ConnectToSource(extractNode.ValueOut("2"));
            
            return combineNode.FirstValueOut().ExpectedType(ExpectedType.Float3);
        }
        
        public static void AddSpaceConversionNodes(UnitExporter unitExporter, GltfInteractivityUnitExporterNode.ValueOutputSocketData unitySpaceVector3, out GltfInteractivityUnitExporterNode.ValueOutputSocketData convertedVector3Socket)
        {
            var extractNode = unitExporter.CreateNode( new Math_Extract3Node());
            extractNode.ValueIn("a").ConnectToSource(unitySpaceVector3);
            convertedVector3Socket = AddSpaceConversionNodes(unitExporter, extractNode);
        }
        
        public static void AddSpaceConversionNodes(UnitExporter unitExporter, ValueInput unitySpaceVector3, out GltfInteractivityUnitExporterNode.ValueOutputSocketData convertedVector3Socket)
        {
            var extractNode = unitExporter.CreateNode( new Math_Extract3Node());
            extractNode.ValueIn("a").MapToInputPort(unitySpaceVector3);
            convertedVector3Socket = AddSpaceConversionNodes(unitExporter, extractNode);  
        }
        
        #endregion

        
        #region Rotation Space Conversion
        
        public static void AddRotationSpaceConversionNodes(UnitExporter unitExporter, GltfInteractivityUnitExporterNode.ValueOutputSocketData unitySpaceQuaternion, out GltfInteractivityUnitExporterNode.ValueOutputSocketData convertedQuaternion)
        {
            var multiplyNode = unitExporter.CreateNode(GenericUnitExport.GetAutoGeneratedSchema("math/mul"));
            multiplyNode.ValueIn("a").ConnectToSource(unitySpaceQuaternion).SetType(TypeRestriction.LimitToFloat4);
            multiplyNode.ValueIn("b").SetValue(new Quaternion(1f, -1f, -1f, 1f)).SetType(TypeRestriction.LimitToFloat4);
            convertedQuaternion = multiplyNode.FirstValueOut().ExpectedType(ExpectedType.Float4);
        }
        
        public static void AddRotationSpaceConversionNodes(UnitExporter unitExporter, ValueInput unitySpaceQuaternion, out GltfInteractivityUnitExporterNode.ValueOutputSocketData convertedQuaternion)
        {
            var multiplyNode = unitExporter.CreateNode(GenericUnitExport.GetAutoGeneratedSchema("math/mul"));
            multiplyNode.ValueIn("a").MapToInputPort(unitySpaceQuaternion).SetType(TypeRestriction.LimitToFloat4);
            multiplyNode.ValueIn("b").SetValue(new Quaternion(1f, -1f, -1f, 1f)).SetType(TypeRestriction.LimitToFloat4);
            convertedQuaternion = multiplyNode.FirstValueOut().ExpectedType(ExpectedType.Float4);
        }
        
        #endregion
    }
}