using System;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityGLTF.Interactivity.Schema;

namespace UnityGLTF.Interactivity.Export
{
    public class Transform_TranslateUnitExport : IUnitExporter
    {
        public Type unitType { get; }
        
        [InitializeOnLoadMethod]
        private static void Register()
        {
            InvokeUnitExport.RegisterInvokeExporter(typeof(Transform), nameof(Transform.Translate), new Transform_TranslateUnitExport());
        }
        
        public void InitializeInteractivityNodes(UnitExporter unitExporter)
        {
           var unit = unitExporter.unit as Unity.VisualScripting.InvokeMember;
           
           var getTranslation = unitExporter.CreateNode(new Pointer_GetNode());
           
           unitExporter.SetupPointerTemplateAndTargetInput(GltfInteractivityNodeHelper.IdPointerNodeIndex,
               unit.target, getTranslation,
               "/nodes/{" + GltfInteractivityNodeHelper.IdPointerNodeIndex + "}/translation");
           
           var add = unitExporter.CreateNode(new Math_AddNode());
     
           unitExporter.MapInputPortToSocketName(Pointer_GetNode.IdValue, getTranslation, Math_AddNode.IdValueB, add);
           if (unit.valueInputs.Skip(1).First().type == typeof(Vector3))
           {
               // translate value is a vector3
               unitExporter.MapInputPortToSocketName(unit.valueInputs.Skip(1).First(), Math_AddNode.IdValueA, add);
           }
           else
           {
               // translate value is separate floats
               GltfInteractivityUnitExporterNode combine3;
               if (GenericUnitExport.TryGetAutoGeneratedSchema("math/combine3", out var combine3Schema))
               {
                   combine3 = unitExporter.CreateNode(combine3Schema);
   
                   unitExporter.MapInputPortToSocketName(unit.valueInputs[1], "a", combine3);
                   unitExporter.MapInputPortToSocketName(unit.valueInputs[2], "b", combine3);
                   unitExporter.MapInputPortToSocketName(unit.valueInputs[3], "c", combine3);
                   
                   unitExporter.MapInputPortToSocketName("value", combine3, Math_AddNode.IdValueA, add);
               }
               else
               {
                   Debug.LogError("Schema not found for math/combine3");
               }
           }
           //TODO: translate of non self
           
           var setTranslation = unitExporter.CreateNode(new Pointer_SetNode());
           
           unitExporter.MapInputPortToSocketName(unit.enter, Pointer_SetNode.IdFlowIn, setTranslation);
           unitExporter.MapOutFlowConnectionWhenValid(unit.exit, Pointer_SetNode.IdFlowOut, setTranslation);
           
           unitExporter.SetupPointerTemplateAndTargetInput(GltfInteractivityNodeHelper.IdPointerNodeIndex,
               unit.target, setTranslation,
               "/nodes/{" + GltfInteractivityNodeHelper.IdPointerNodeIndex + "}/translation");

           unitExporter.MapInputPortToSocketName(Math_AddNode.IdOut, add, Pointer_SetNode.IdValue, setTranslation);
           
           unitExporter.MapOutFlowConnectionWhenValid(unit.exit, Pointer_SetNode.IdFlowOut, setTranslation);
        }
    }
}